### ISSUE TITLE
Cleanup steps for next release - draft release, docs versions

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeymarker#33]
Things to do:
- [x] Fix anything circleci need to fix to do a tag-based build
- [x] Update docs to point to the correct github releases page
- [x] Tweak docs scripts to update things correctly in this new world
- [x] Re-aim old honeymarker links in infra to the github page so people with old links get to the right place
- [x] Profit!

**Comment by kentquirk** [comment]
Things to do:
- [ ] Fix anything circleci need to fix to do a tag-based build
- [ ] Get the binaries uploaded to S3 and reflected in the releases page
- [ ] Update docs to point to the correct github releases page
- [ ] Tweak docs scripts to update things correctly in this new world
- [ ] Re-aim old honeymarker links in infra to the github page so people with old links get to the right place
- [ ] Profit!

**Comment by JamieDanielson** [comment]
All done ✅
