### ISSUE TITLE
[Enhancement] Honeymarker in a public container registry

### ISSUE THREAD

**Issue by minac** [honeycombio/honeymarker#4]
It would be useful to have the `honeymarker` binary packaged in a docker image in a public registry like Docker Hub. 

The work does not seem very complex, but if `honeymarker` was made available by Honeycomb it would be more reputable for anyone looking for it in a public registry.

**Comment by minac** [comment]
👋 again. I noticed that other docker images by Honeycomb are already in [Docker Hub](https://hub.docker.com/u/honeycombio). Maybe this one could go there as well?

**Comment by minac** [comment]
Thanks, @paulosman! 

The Dockerfile looks nice, but nothing is up on Docker Hub (or another registry). Could it please be uploaded there?

**Comment by paulosman** [comment]
Reopening as a task for consideration by the @honeycombio/telemetry-team 

Context: #15 created an up-to-date dockerfile but did not contain any CI changes necessary to publish it to a registry

**Comment by antifuchs** [comment]
I too would love this, as it unlocks very speedy usage of honeymarker in github actions.

**Comment by minac** [comment]
Thanks, @MikeGoldsmith! I still don't see it in Docker Hub though... https://hub.docker.com/u/honeycombio

**Comment by MikeGoldsmith** [comment]
Hey @minac - we had an issue with user credentials which we resolved yesterday. Both the 0.2.0 and latest images have now been published:
https://hub.docker.com/r/honeycombio/honeymarker/tags?page=1&ordering=last_updated
