### ISSUE TITLE
Pull --writekey From Environment Variable

### ISSUE THREAD

**Issue by elliottpope** [honeycombio/honeymarker#75]
**Is your feature request related to a problem? Please describe.**

I am trying to use Honeymarker for some Kubernetes automation. It would be easier to source the Honeycomb API key from a Secret injected into the container environment. Since the provided container is built from `scratch` there is no available Shell to do environment variable expansion 

**Describe the solution you'd like**

The underlying command line option parser allows for specifying environment variable defaults (https://github.com/jessevdk/go-flags/issues/309). We could add `env:"HONEYCOMB_API_KEY"` to the `WriteKey` struct tag [here](https://github.com/honeycombio/honeymarker/blob/main/main.go#L18) to pull from the environment I believe

**Describe alternatives you've considered**

I don't want to put the API key in plain text in the K8s manifest since this won't allow me to swap out the key value in different environments (i.e. dev, test, production) while keeping the same manifest definition

**Additional context**

**Comment by jharley** [comment]
Closed by #76
